---
- name: Build list of images
  ansible.builtin.find:
    paths:
      - /home/runner/work/ansible-meeting-bgs/ansible-meeting-bgs/images/
      - /home/runner/work/ansible-meeting-bgs/ansible-meeting-bgs/gifs/
    recurse: true
    patterns: '*.png,*.jpg,*.jpeg,*.gif'
  register: images

- name: dump images
  ansible.builtin.debug:
    var: images

- name: template readme
  ansible.builtin.template:
    src: readme.md.j2
    dest: /home/runner/work/ansible-meeting-bgs/ansible-meeting-bgs/README.md

