---
- name: Build list of images
  ansible.builtin.find:
    paths: /tmp/ansible-meeting-bgs/
    recurse: true
    patterns: '*.png,*.jpg,*.jpeg'
  register: images

- name: list images
  debug:
    var: images

- name: template readme
  ansible.builtin.template:
    src: readme.md.j2
    dest: /tmp/readme.md
