---
- name: Build list of images
  ansible.builtin.find:
    paths: /home/runner/work/ansible-meeting-bgs/ansible-meeting-bgs/images/
    recurse: true
    patterns: '*.png,*.jpg,*.jpeg'
  register: images

- name: template readme
  ansible.builtin.template:
    src: readme.md.j2
    dest: /home/runner/work/ansible-meeting-bgs/ansible-meeting-bgs/README.md

# - name: push readme
#   ansible.builtin.shell:
#     cmd: |
#       git config user.name github-actions
#       git config user.email github-actions@github.com
#       git add /tmp/ansible-meeting-bgs/README.md
#       git commit -m 'auto-generate README.md'
#       git push origin main
