---
- name: Build list of images
  ansible.builtin.find:
    paths: /tmp/ansible-meeting-bgs/
    recurse: true
    patterns: '*.png,*.jpg,*.jpeg'
  register: images

- name: list images
  debug:
    var: images
