---
- name: Build list of images
  ansible.builtin.find:
    paths: /tmp/ansible-meeting-bgs/
    recurse: true
    patterns: '*.png,*.jpg,*.jpeg'
  register: images

- name: template readme
  ansible.builtin.template:
    src: readme.md.j2
    dest: /tmp/ansible-meeting-bgs/README.md

- name: commit new readme
  ansible.builtin.shell:
    cmd: git config user.email github-actions@github.com

  ansible.builtin.shell:
    cmd: git config user.name github-actions

  ansible.builtin.shell:
    cmd: git add /tmp/ansible-meeting-bgs/README.md

  ansible.builtin.shell:
    cmd: git commit -m 'auto-generate README.md'

  ansible.builtin.shell:
    cmd: git push origin main
   
