name: build-readme
on: 
  workflow_dispatch:
  push:
    paths:
      - 'images/**'
    branches:
      - main

jobs:
  build-readme-of-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install ansible
        run: sudo apt-get install ansible
      - name: run playbook
        run: ansible-playbook /home/runner/work/ansible-meeting-bgs/ansible-meeting-bgs/.github/workflows/ansible/build-readme.yml
      - name: cat readme
        run: cat /home/runner/work/ansible-meeting-bgs/ansible-meeting-bgs/README.md
      - name: push readme
        run: |
          cd /home/runner/work/ansible-meeting-bgs/ansible-meeting-bgs
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add /home/runner/work/ansible-meeting-bgs/ansible-meeting-bgs/README.md
          git commit -m "readme generated"
          git push

